# Generated by Django 5.2.13 on 2026-04-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('ARCHIVE', 'archive'), ('RESTORE', 'restore'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
