# Generated by Django 5.2.13 on 2026-04-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('ARCHIVE', 'Archive'), ('RESTORE', 'Restore'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
