# Generated by Django 5.2.13 on 2026-04-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype_id', models.CharField(max_length=20, unique=True)),
                ('dtype_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'document_types',
            },
        ),
    ]
