# Generated by Django 5.2.13 on 2026-04-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtypes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentTypes',
            new_name='Dtype',
        ),
    ]
