# Generated by Django 5.2.9 on 2026-02-05 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0003_alter_department_table'),
        ('ranks', '0001_initial'),
        ('roles', '0001_initial'),
        ('stypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100, unique=True)),
                ('staff_name', models.CharField(max_length=100, unique=True)),
                ('staff_email', models.EmailField(max_length=254, unique=True)),
                ('staff_address', models.CharField(max_length=100)),
                ('staff_ph_number', models.CharField(max_length=100, unique=True)),
                ('staff_gender', models.CharField(max_length=10)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='departments.department')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='ranks.rank')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='roles.role')),
                ('stype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='stypes.stype')),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
    ]
