# Generated by Django 5.2.13 on 2026-06-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmark_id', models.CharField(max_length=10, unique=True)),
                ('landmark_name', models.CharField(max_length=50, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'landmarks',
            },
        ),
    ]
