# Generated by Django 5.2.13 on 2026-06-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=10, unique=True)),
                ('location_name', models.CharField(max_length=50, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.DeleteModel(
            name='Landmark',
        ),
    ]
