# Generated by Django 5.2.13 on 2026-06-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_delete_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='locations/'),
        ),
    ]
