# Generated by Django 5.2.13 on 2026-06-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_location_location_id_location_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='created_time',
        ),
    ]
