# Generated by Django 5.2.13 on 2026-06-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_remove_location_created_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
