# Generated by Django 5.2.13 on 2026-06-21 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_department_created_at_department_updated_at'),
        ('locations', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type_name', models.CharField(max_length=225, unique=True)),
            ],
            options={
                'db_table': 'location_types',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='departments.department'),
        ),
    ]
