# Generated by Django 5.2.13 on 2026-06-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_location_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_type',
        ),
    ]
