# Generated by Django 5.2.13 on 2026-06-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_remove_location_location_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationType',
        ),
    ]
