# Generated by Django 5.2.13 on 2026-06-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_delete_locationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
