# Generated by Django 5.2.9 on 2026-02-04 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=100, unique=True)),
                ('department_name', models.CharField(max_length=100, unique=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='rooms.room')),
            ],
        ),
    ]
