# Generated by Django 5.2.9 on 2026-02-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_room'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
    ]
