# Generated by Django 5.2.9 on 2025-12-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moguser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
