# Generated by Django 5.2.9 on 2025-12-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_moguser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moguser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
