# Generated by Django 5.2.9 on 2026-01-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_moguser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moguser',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
