# Generated by Django 5.2.13 on 2026-05-02 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_moguser_role'),
        ('staffs', '0002_staff_created_at_staff_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='moguser',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='staffs.staff'),
        ),
    ]
