# Generated by Django 5.2.9 on 2026-02-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=100, unique=True)),
                ('role_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
    ]
