# Generated by Django 5.2.13 on 2026-04-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('parent_id', models.IntegerField()),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
