# Generated by Django 5.2.13 on 2026-04-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_parent_id_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.CharField(default='-', max_length=20, unique=True),
        ),
    ]
