# Generated by Django 5.2.13 on 2026-04-22 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_remove_category_parent_id_category_parent'),
        ('staffs', '0002_staff_created_at_staff_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=20, unique=True)),
                ('document_name', models.CharField(max_length=20, unique=True)),
                ('document_path', models.CharField(max_length=220, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.category')),
                ('staffs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staffs.staff')),
            ],
        ),
    ]
