# Generated by Django 5.2.13 on 2026-04-27 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('dtypes', '0002_rename_documenttypes_dtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dtypes.dtype'),
        ),
    ]
