# Generated by Django 5.2.13 on 2026-04-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_dtype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='documents',
        ),
    ]
