# Generated by Django 5.2.13 on 2026-04-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='staffs',
            new_name='staff',
        ),
    ]
