# Generated by Django 5.2.13 on 2026-04-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_path',
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
