# Generated by Django 5.2.13 on 2026-04-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_document_document_path_document_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='staff',
        ),
    ]
