# Generated by Django 5.2.13 on 2026-04-28 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_document_staff'),
        ('staffs', '0002_staff_created_at_staff_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staffs.staff'),
        ),
    ]
