# Generated by Django 5.2.13 on 2026-04-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.CharField(max_length=225),
        ),
    ]
