# Generated by Django 5.2.13 on 2026-04-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_document_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expired_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
