# Generated by Django 5.2.13 on 2026-04-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_document_archived_at_document_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='restore_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
