# Generated by Django 5.2.9 on 2026-02-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
    ]
