# Generated by Django 5.2.9 on 2026-02-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(default=0),
        ),
    ]
