# Generated by Django 5.2.13 on 2026-04-26 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('rooms', '0004_room_created_at_room_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='buildings.building'),
        ),
    ]
